todo/task/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

# todo: check and rename https://betterprogramming.pub/10-best-practices-for-naming-rest-api-endpoints-442ae592a3a0
urlpatterns = [
    path('', Index.as_view(), name="main_page"),
    path('Tasks/', LookMyTasks.as_view(), name="task_page"),
    path('CreateTask/', CreateTask.as_view(), name="task_create"),
    path('DeleteTask/task-<int:pk>', DeleteTask.as_view(), name="task_delete"),
    path('UpdateTask/task-<int:pk>', UpdateTask.as_view(), name="edit_task"),
    path('Login/', LoginAccount.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="main_page"), name="logout"),
    path('registration/', RegisterAccount.as_view(), name="registration"),
    path('<slug:slug>/profile/', ProfileCheck.as_view(), name="check"),
    path('<slug:slug>/edit-profile/', ProfileEdit.as_view(), name="edit"),
    path('Rating/', Rating.as_view(), name="rating"),
    path('complete/task-<int:pk>', complete, name='complete'),
    path('<slug:slug>/check/', CheckSomebodyProfile.as_view(), name='check_somebody'),
    path('DeleteDoneTasks/', delete_all_completed_tasks, name='DeleteDoneTasks'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]
handler404 = "task.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/task/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils.text import slugify

# todo: write all comments in english

# Розширений юзер
class CustomUser(AbstractUser):
    # Валідатор для номеру телефона
    # todo: that's cool, but there is also a phone field in django exists
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="False number. Example: +380000000000")
    phone = models.CharField(validators=[phone_regex], blank=True, max_length=15)
    score = models.IntegerField(default=0)
    bio = models.TextField(blank=True)
    # todo: its better to set constant in setting like `settings.MEDIA_ROOT`
    photo = models.ImageField(upload_to='UserIcon/%Y/%m/%d', blank=True)
    slug = models.SlugField(blank=True)

    # Для слагів
    def save(self, *args, **kwargs):
        # todo: check pre_save signal, it's not better for real, but it's a good practice
        if not self.slug:
            self.slug = slugify(self.username)
        super().save(*args, **kwargs)


# Модель завдання
# todo: for class its better to use tripple quotes, like this:
class Task(models.Model):
    """Save task details in db."""
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    # todo: boolean fields has own naming rules
    #  (https://stackoverflow.com/questions/47996388/python-boolean-methods-naming-convention)
    complete = models.BooleanField(default=False)
    creation_data = models.DateTimeField(auto_now_add=True)
    to_do_date = models.DateTimeField()

    def __str__(self):
        return f"{self.title}"

    # Для адмінки
    class Meta:
        verbose_name = 'Завдання'
        verbose_name_plural = "Завдання"
        ordering = ['to_do_date', 'title']


# Модель для фото на головне меню
class SiteImages(models.Model):
    caption = models.CharField(max_length=100, blank=True)
    photo = models.ImageField(upload_to="SitePhotos")

todo/task/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import *
from django import forms
import re


# Форма для створення завдання
class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'to_do_date']
        widgets = {
            'title': forms.TextInput(attrs={"class": "input_field inp", "placeholder": "Введіть назву завдання..."}),
            'description': forms.Textarea(
                attrs={"class": "task_field inp", "placeholder": "Введіть суть завдання..."}),
            # todo: for all python code use either double or single quotes.
            # todo: use black, flake8 or pre-commit to do it automatically
            'to_do_date': forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S',
                                              attrs={"class": "date_field inp", "placeholder": "DD.MM.YYYY hh:mm",
                                                     "type": "datetime-local"})
        }
        labels = {
            'title': "Назва завдання",
            'description': "Опис",
            'to_do_date': "Deadline"
        }


# Форма для реєстрації юзера
class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

    def clean_password2(self):
        # todo: i know its from django docs, but better naming helps to scale code
        # todo: so use password and confirmed_password
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Паролі не збігаються")
        return password2


# Форма для зміни інформації у профілі
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'phone', 'first_name', 'last_name', 'bio', 'photo')
        labels = {
            'email': "Email:",
            'phone': "Номер телефону",
            'bio': "Біографія",
            'photo': "Завантажити нове фото"
        }
        widgets = {
            'email': forms.TextInput(attrs={"class": "profile-email", "placeholder": "Введіть email..."}),
            'first_name': forms.TextInput(attrs={"placeholder": "Введіть ваше ім'я..."}),
            'last_name': forms.TextInput(attrs={"placeholder": "Введіть ваше прізвище..."}),
            'phone': forms.TextInput(
                attrs={"class": "profile-phone", "placeholder": "Введіть номер телефону...", "type": "tel"}),
            'bio': forms.Textarea(
                attrs={"class": "profile-bio", "placeholder": "Введіть вашу біографію", "rows": 5, "columns": 15}),
            'photo': forms.FileInput(attrs={"class": "photo_input"})
        }

    # Валідатори. Перевіряє на наявність усього, окрім букв
    # todo: reuse functions, do not duplicate code, like this:
    # def validate_name(self, name, error_message):
    #     if re.search(r"\d", name) or re.search(r"\W", name) or re.search("_", name):
    #         raise ValidationError(error_message)
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        # addition: self.validate_name(last_name, "Прізвище не має містити цифри і різні знаки...")
        if re.search(r"\d", last_name) or re.search(r"\W", last_name) or re.search("_", last_name):
            raise ValidationError("Прізвище не має містити цифри і різні знаки...")
        return last_name

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if re.search(r"\d", first_name) or re.search(r"\W", first_name) or re.search("_", first_name):
            raise ValidationError("Ім'я не має містити цифри і різні знаки...")
        return first_name

todo/task/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateTaskForm, SignUpForm, ProfileEditForm
from .models import *
from django.http import Http404, HttpResponseNotFound
from django.template import RequestContext


# Головна сторінка
class Index(TemplateView):
    template_name = "task/index.html"


# Список усіх завдань
# todo: use better naming, such as TaskView AND
# class based views are recommended when you need to handle multiple requests at one point
# check https://stackoverflow.com/questions/27688107/how-does-class-based-view-with-multiple-methods-work-with-urls-in-django
class LookMyTasks(LoginRequiredMixin, ListView):
    template_name = "task/MyTasks.html"
    model = Task
    context_object_name = "tasks"

    # todo: use django filter(if one's exists) for filtering by fields
    # and queryset = ... or :
    # def get_queryset(self):
    #     return Task.objects.filter(user=self.request.user).order_by("complete", "-pk")

    # Фільтруємо по юзеру, виконуємо гет запит для поля з пошуком записів.
    # Рахуємо кількість виконаних задач, які є в списку
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = context['tasks'].filter(user=self.request.user).order_by('complete', '-pk')
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__contains=search_input)
        context['search_input'] = search_input
        # todo: why do you use exact? complete=True
        context['done'] = Task.objects.filter(user=self.request.user, complete__exact=True).count()
        context['all'] = Task.objects.filter(user=self.request.user).count()
        return context


# Створення завдання
class CreateTask(LoginRequiredMixin, CreateView):
    template_name = "task/CreateTask.html"
    form_class = CreateTaskForm
    success_url = reverse_lazy('task_page')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateTask, self).form_valid(form)


# Видалення завдання
class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task/DeleteTask.html'
    success_url = reverse_lazy('task_page')

    # Перевіряємо чи має доступ юзер до цієї сторінки(щоб через посилання не можна було зайти на чужі завдання)
    # Якщо це не він, піднімаємо помилку
    def get_object(self, queryset=None):
        obj = super(DeleteTask, self).get_object()
        # todo: that's cool that you raised error here
        # but check if it could be solved just using get_queryset()
        if obj.user != self.request.user:
            raise Http404("Точно працює")
        return obj


# Ономлення завдання
class UpdateTask(LoginRequiredMixin, UpdateView):
    template_name = 'task/CreateTask.html'
    model = Task
    form_class = CreateTaskForm
    success_url = reverse_lazy('task_page')

    # Так само як і DeleteTask
    # todo: the same )0
    def get_object(self, queryset=None):
        obj = super(UpdateTask, self).get_object()
        if obj.user != self.request.user:
            raise Http404("Точно працює")
        return obj


# Позначити як виконане(або не виконано)
# todo: pleeeeeease!!!!!! add it to TaskView class (dont mix functional and class-based methods in views)
def complete(request, pk):
    # Перевірка юзера
    if request.user != Task.objects.get(pk=pk).user:
        raise Http404
    data = get_object_or_404(Task, pk=pk)
    # todo: you have request.user, why getting it here
    person = get_object_or_404(CustomUser, username=data.user)
    # Виконали/не виконали
    # Додаємо і віднімаємо + зберігаємо для того, щоб при видаленні завдання не втрачався бал
    if not data.complete:
        data.complete = True
        person.score += 1
    else:
        data.complete = False
        person.score -= 1
    person.save()
    data.save()
    return redirect('task_page')


# Login
class LoginAccount(LoginView):
    template_name = "task/Login.html"
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy('main_page')


# Registration
class RegisterAccount(FormView):
    template_name = "task/Registration.html"
    form_class = SignUpForm
    success_url = reverse_lazy("main_page")

    # Якщо зареєструвалися, виходимо зі старого аккаунту і переходимо на новий
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            logout(self.request)
            login(self.request, user)
        return super(RegisterAccount, self).form_valid(form)


# Власний профіль
class ProfileCheck(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "task/ProfileCheck.html"
    context_object_name = "profile"

    # Перевірка юзера/піднімаємо помилку
    def get_object(self, queryset=None):
        obj = super(ProfileCheck, self).get_object(queryset=queryset)
        if obj.username != self.request.user.username:
            raise Http404("Точно працює")
        return obj


# Редагування профілю
class ProfileEdit(LoginRequiredMixin, UpdateView):
    template_name = "task/ProfileEdit.html"
    model = CustomUser
    form_class = ProfileEditForm
    success_url = reverse_lazy('main_page')

    # Перевірка юзера/піднімаємо помилку
    def get_object(self, queryset=None):
        obj = super(ProfileEdit, self).get_object(queryset=queryset)
        if obj.username != self.request.user.username:
            raise Http404("Точно працює")
        return obj


# Рейтингова сторінка
class Rating(ListView):
    template_name = "task/Rating.html"
    context_object_name = "user_rating"
    model = CustomUser

    # видаємо перших 20 людей по балах(+ імені)
    def get_context_data(self, *, object_list=None, **kwargs):
        # todo: remove getting all users
        all_user = CustomUser.objects.all()
        context = super().get_context_data(**kwargs)
        context['user_rating'] = context['user_rating'].order_by('-score', '-username')[:20]
        if self.request.user.is_authenticated:
            # todo: use context['user_position']
            context['you_position'] = list(context['user_rating']).index(self.request.user) + 1
        return context


# Перевірити чийсь профіль з рейтингу
class CheckSomebodyProfile(DetailView):
    template_name = "task/CheckSomebodyProfile.html"
    model = CustomUser
    context_object_name = 'profile'

# todo: use redirect to tasks list if user has no permissions to one
# Підгружаємо свій темплейт для 404 помилки
def page_not_found_view(request, exception):
    return render(request, 'NoPermissionPage.html', status=404)


# Видалення всіх записів, які виконані зі списку
def delete_all_completed_tasks(request):
    if request.method == "POST":
        # Беремо всі записи даного юзера, які виконані і видаляємо
        Task.objects.filter(user=request.user, complete=True).delete()
        return redirect('task_page')
    return render(request, 'task/DeleteDoneTasks.html')

todo/task/templates/task/CheckSomebodyProfile.html
{% extends 'base.html' %}

{% block main %}
<div class="profile-container" style="padding-bottom: 25px;">
    {% include 'include/_check_your_somebody_profiles.html' %}
    <div class="score">
        <strong>Кількість балів:</strong> <br>{{ profile.score }}
    </div>
</div>
{% include "include/_footer.html" %}
{% endblock %}

todo/task/templates/task/CreateTask.html
{% extends "base.html" %}

{% block main %}
<form method="post" class="form">
    {% csrf_token %}
    <div>
        {% for item in form %}
        <div class="form-element">
            {{ item.label_tag }}
            {{ item }}
            {% if item.errors %}
            <div class="error">
                * Введіть коректне значення
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    <input class="btn-add-task" type="submit" value="Записати">
</form>
{% endblock %}

todo/task/templates/task/DeleteDoneTasks.html
{% load task_tags %}
{% get_text_for_delete_forms 1 as text %}
{% include 'include/_delete_task_or_tasks.html' %}

todo/task/templates/task/DeleteTask.html
{% load task_tags %}
{% get_text_for_delete_forms 0 as text %}
{% include 'include/_delete_task_or_tasks.html' %}

todo/task/templates/task/Login.html
{% extends 'base.html' %}

{% block header %}
<div class="header">
    <div class="nav-first-part">
        <a href="{% url 'main_page' %}">Повернутися назад</a>
    </div>
</div>
{% endblock %}

{% block main %}
<form method="post" class="login-class">
    {% csrf_token %}
    {% for item in form %}
    <label>{{ item.label }}</label>
    {{ item }}
    {% endfor %}
    {% if form.errors %}
    <div class="error">
        Перевірте ім'я та пароль
    </div>
    {% endif %}
    <input class="login-btn" type="submit" value="Увійти">
</form>
{% endblock %}

todo/task/templates/task/MyTasks.html
{% extends "base.html" %}

{% block main %}
{% load task_tags %}
<div class="main-body">
    <form class="search-form" method="get">
        <input class="search-field" type="text" name="search-area" value="{{ search_input }}" autocomplete="off">
        <input class="search-btn" type="submit" value="Search">
    </form>
    <div class="all-btn">
        <a class="add-btn" href="{% url 'task_create' %}">Додати завдання</a>
        <a class="add-btn" href="{% url 'DeleteDoneTasks' %}">Видалити виконані завдання</a>
    </div>
    <div class="done-task">
        <div class="done">Виконано: {{ done }}</div>
        <div class="all">Усіх: {{ all }}</div>
    </div>
    <div class="cards">
        {% if tasks|length > 0 %}
        {% for task in tasks %}
        <div class="card" {% if task.complete %} style="opacity: 0.7;" {% endif %}>
            {% if not task.title %}
            <div class="card-header" style="color: rgb(189, 189, 189);">
                Без назви
            </div>
            {% else %}
            {% if task.complete %}
            <div class="card-header" style="text-decoration: line-through;">
                {{ task.title }}
            </div>
            {% else %}
            <div class="card-header">
                {{ task.title }}
            </div>
            {% endif %}
            {% endif %}
            {% if not task.description %}
            <div class="main" style="color: rgb(189, 189, 189);">
                Без опису
            </div>
            {% else %}
            <div class="main">
                {{ task.description|linebreaks }}
            </div>
            {% endif %}
            <div class="card-footer">
                <div class="task-info">
                    <div class="first-part">
                        Deadline: {{ task.to_do_date }}
                    </div>
                </div>
                <div class="settings-btn">
                    <a class="btn complete" href="{% url 'complete' task.pk %}">
                        {% if task.complete %}
                        Позначити як не виконане
                        {% else %}
                        Позначити як виконане
                        {% endif %}
                    </a>
                    <a class="btn edit" href="{% url 'edit_task' task.pk %}">Редагувати</a>
                    <a class="btn delete" href="{% url 'task_delete' task.pk %}">Видалити</a>
                </div>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <div class="card-empty">
            <p class="empty"> Створіть власні завдання та виконуйте їх</p>
        </div>
        {% endif %}
    </div>
</div>
{% include "include/_footer.html" %}
{% endblock %}

todo/task/templates/task/ProfileCheck.html
{% extends 'base.html' %}

{% block main %}
<div class="profile-container">
    {% include 'include/_check_your_somebody_profiles.html' %}
    <div class="score">
        <strong>Ваша кількість балів:</strong> <br>{{ profile.score }}
    </div>
    <a class="profile-edit-btn" href="{% url 'edit' request.user.slug %}">Редагувати</a>
</div>
{% include "include/_footer.html" %}
{% endblock %}

todo/task/templates/task/ProfileEdit.html
{% extends 'base.html' %}

{% block main %}
<form method="post" class="edit-container" enctype="multipart/form-data">
    {% csrf_token %}
    {% for item in form %}
    {% if forloop.last %}
    <div class="choose-file">
        <label for="id_photo" class="file-label">{{ item.label }}</label>
        {{ item }}
    </div>
    {% else %}
    <label>{{ item.label }}</label>
    {{ item }}
    {% if item.errors %}
    <div class="error" style="margin: -10px;">
        {{ item.errors }}
    </div>
    {% endif %}
    {% endif %}
    {% endfor %}
    <input class="edit-btn" type="submit" value="Зберегти">
</form>
<script>
const file = document.querySelector('#id_photo');
file.addEventListener('change', (e) => {
  const [file] = e.target.files;
  const { name: fileName, size } = file;
  const fileSize = (size / 1000).toFixed(2);
  const fileNameAndSize = `${fileName} - ${fileSize}KB`;
  document.querySelector('.file-label').textContent = fileNameAndSize;
});

</script>
{% endblock %}

todo/task/templates/task/Rating.html
{% extends 'base.html' %}

{% block main %}
<!--https://w3schoolsua.github.io/html/html_css.html-->
<div class="rating-container">
    <div class="main-title">Рейтинг</div>
    <div class="rating-title">
        <div class="count-title">Місце:</div>
        <div class="score-title">Кількість балів:</div>
    </div>
    {% for item in user_rating %}
    <div class="rating-element">
        <div class="info-rating count">{{ forloop.counter }}</div>
        <div class="container-info-rating">
            {% if item.photo %}
            <img width="55px" height="55px" src=" {{ item.photo.url }}">
            {% else %}
            <img width="55px" height="55px"
                 src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
            {% endif %}
            <a href="{% url 'check_somebody' item.slug %}" class="info-rating rating-user">{{ item.username }}</a>
            <div class="info-rating rating-score">{{ item.score }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% if request.user.is_authenticated %}
<div class="rating-container">
    <div class="rating-title">
        <div class="count-title">Ваше місце:</div>
        <div class="score-title">Ваші бали:</div>
    </div>
    <div class="rating-element">
        <div class="info-rating count">{{ you_position }}</div>
        <div class="container-info-rating">
            {% if request.user.photo %}
            <img width="55px" height="55px" src=" {{ request.user.photo.url }}">
            {% else %}
            <img width="55px" height="55px"
                 src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
            {% endif %}
            <a href="{% url 'check' request.user.slug %}" class="info-rating rating-user">{{ request.user.username }}</a>
            <div class="info-rating rating-score">{{ request.user.score }}</div>
        </div>
    </div>
</div>
{% endif %}
{% include 'include/_footer.html' %}
{% endblock %}

todo/task/templates/task/Registration.html
{% extends 'base.html' %}

{% block header %}
<div class="header">
    <div class="menu-header" style="font-size: 25px; font-weight: bold; border-bottom: 2px solid gray">Меню</div>
    <div class="nav-first-part">
        <a href="{% url 'main_page' %}">Повернутися назад</a>
    </div>
</div>
{% endblock %}

{% block main %}
<form method="post" class="login-class">
    {% csrf_token %}
    {% for item in form %}
    <label>{{ item.label }}</label>
    {{ item }}
    {% if item.errors %}
    <!-- Розібратися з помилками -->
    <div class="error" style="margin: -10px 10px -10px -10px;">
        {{ item.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <input class="login-btn" type="submit" value="Зареєструватися">
</form>
{% endblock %}

todo/task/templates/task/index.html
{% extends 'base.html' %}

{% block main %}
{% load task_tags %}
<div class="index-container">
    <div class="index-text">
        Проект написаний на фреймворку Django. Тестовий сайт.
    </div>
    <div class="first-p" style="padding-bottom: 150px; border-bottom: 5px solid white; margin-bottom: 150px;">
        {% photo_tag 1 as img %}
        <img height="300px" width="500px"
             src="{{ img.photo.url }}">
        <div class="info-container">
            <div class="index-title">Про сайт</div>
            <div class="index-story">Цей сайт слугує особистим записником задач. Він містить потрібний функціонал та має
                можливість вести аккаунт для змагання з іншими учасниками.
            </div>
        </div>
    </div>
    <div class="first-p" style="margin-bottom: 50px;">
        <div class="info-container">
            <div class="index-title">Про завдання</div>
            <div class="index-story">У вас з'являється робоче місце. Тут будуть знаходитися всі ваші завдання.
                Натисніть кнопку "Додати завдання" та розпочніть виконувати їх вже сьогодні.
            </div>
        </div>
        {% photo_tag 2 as img %}
        <img height="300px" width="500px"
             src="{{ img.photo.url }}">
    </div>
    <div class="first-p" style="padding-bottom: 150px; border-bottom: 5px solid white; margin-bottom: 150px;">
        {% photo_tag 3 as img %}
        <img height="300px" width="500px"
             src="{{ img.photo.url }}">
        <div class="info-container">
            <div class="index-title">Про редагування</div>
            <div class="index-story">Ви можете змінити термін виконання або взагалі змінити саме завдання за допомогою
                кнопки редагувати. Після успішного виконання можна видалити завдання або позначити як "Виконане".
            </div>
        </div>
    </div>
    <div class="first-p" style="padding-bottom: 150px; border-bottom: 5px solid white; margin-bottom: 150px;">
        <div class="info-container">
            <div class="index-title">Про рейтинг</div>
            <div class="index-story">Також ви можете позмагатися з іншими учасниками сайту,
                виконуючи СВОЇ завдання та отримуючи
                бали. Ваші результати зберігаються в профілі та можуть попасти в рейтинг.
            </div>
        </div>
        {% photo_tag 4 as img %}
        <img height="300px" width="500px"
             src="{{ img.photo.url }}">
    </div>
    <div class="first-p" style="padding-bottom: 150px; border-bottom: 5px solid white; margin-bottom: 150px;">
        {% photo_tag 5 as img %}
        <img height="300px" width="500px"
             src="{{ img.photo.url }}">
        <div class="info-container">
            <div class="index-title">Про профіль</div>
            <div class="index-story">Фінальним бонусом є те, що ви можете додати інформацію
                про себе в профілі, редагувати її та переглядати профілі учасників, які потрапили в рейтинг.
            </div>
        </div>
    </div>
    <div class="reg-log-container">
        <div class="registration-login-container">
            {% photo_tag 6 as img %}
            <img class="rl-img" src="{{ img.photo.url }}"
                 height="150px" width="150px">
            <div class="registration-login-container-title">
                Маєте аккаунт? Ласкаво просимо!
            </div>
            <a class="rl-btn" href="{% url 'login' %}">Увійти</a>
        </div>
         <div class="registration-login-container">
             {% photo_tag 7 as img %}
            <img class="rl-img" src="{{ img.photo.url }}"
                 height="150px" width="150px">
            <div class="registration-login-container-title">
                Не маєте аккаунту? Ласкаво просимо!
            </div>
            <a class="rl-btn" href="{% url 'registration' %}">Зареєструватися</a>
        </div>
    </div>
</div>
{% include 'include/_footer.html' %}
{% endblock %}

<!--
Фінальним бонусом є те, що ви можете додати інформацію
про себе в профілі, редагувати її та переглядати профілі учасників, які потрапили в рейтинг.
-->